databases:
  - name: pronet-postgres
    databaseName: profession_db
    plan: free

services:
  # User Service
  - type: web
    name: pronet-user-service
    env: node
    plan: free
    rootDir: services/user-service
    buildCommand: bash render-build.sh
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 3001
      - key: DATABASE_HOST
        fromDatabase:
          name: pronet-postgres
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: pronet-postgres
          property: port
      - key: DATABASE_USER
        fromDatabase:
          name: pronet-postgres
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: pronet-postgres
          property: password
      - key: DATABASE_NAME
        fromDatabase:
          name: pronet-postgres
          property: database
      - key: JWT_SECRET
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        value: dgl4cpuik
      - key: CLOUDINARY_API_KEY
        value: 637454513411741
      - key: CLOUDINARY_API_SECRET
        value: 7JHtL4bTAYqwq7RaQM60Ocf43fw
      - key: GOOGLE_CLIENT_ID
        value: 1075769500266-gee3kfr5mt1obnc06q2c21vamscfcq0t.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        value: 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
      - key: GOOGLE_CALLBACK_URL
        value: https://pronet-user-service.onrender.com/api/auth/google/callback
      - key: FRONTEND_URL
        value: https://pro-net-ten.vercel.app
        
  # API Gateway
  - type: web
    name: pronet-api-gateway
    env: node
    plan: free
    rootDir: services/api-gateway
    buildCommand: bash render-build.sh
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 3000
      - key: USER_SERVICE_URL
        value: https://pronet-user-service.onrender.com
      - key: JWT_SECRET
        generateValue: true
