# databases:
#   - name: pronet-postgres
#     databaseName: profession_db
#     plan: free

services:
  # User Service
  - type: web
    name: pronet-user-service
    runtime: node
    plan: free
    rootDir: services/user-service
    buildCommand: npm install --production=false --legacy-peer-deps && npm run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
      - key: DATABASE_SSL
        value: true
      - key: DATABASE_HOST
        value: dpg-d4askkpe2q1c73b80mrg-a.oregon-postgres.render.com
      - key: DATABASE_PORT
        value: 5432
      - key: DATABASE_USER
        value: profession_db_user
      - key: DATABASE_PASSWORD
        value: A7FSv3naAi5oIJkYlHKiTT5jcoLvkEla
      - key: DATABASE_NAME
        value: profession_db
      - key: JWT_SECRET
        value: "VY2Lf3iix4PILDFNK7HggRhhHIiyQY3qB381Cq0Yui0="
      - key: CLOUDINARY_CLOUD_NAME
        value: dgl4cpuik
      - key: CLOUDINARY_API_KEY
        value: 637454513411741
      - key: CLOUDINARY_API_SECRET
        value: 7JHtL4bTAYqwq7RaQM60Ocf43fw
      - key: GOOGLE_CLIENT_ID
        value: 716006181490-r1fvklb9s9b26nk7jdmf69vf315b9uaa.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        value: 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
      - key: GOOGLE_CALLBACK_URL
        value: https://pronet-user-service-qpe6.onrender.com/api/auth/google/callback
      - key: FRONTEND_URL
        value: https://pro-net-ten.vercel.app
      - key: EMAIL_USER
        value: abenezerforjobs2@gmail.com
      - key: EMAIL_PASSWORD
        value: fzrlxrluiynrujpl
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: false
      - key: GOOGLE_REFRESH_TOKEN
        value: 1//03WvAwhk0kBmvCgYIARAAGAMSNwF-L9IrVrB4IjKBUMWr0aB0DviIeWaHGXXVjwRjCxOdTgdd0nS7dcZWnJJ4FSQT_C5VGSFo1Sk
      - key: RESEND_API_KEY
        value: re_4vTKv6Cz_HZ2iX37wBfEzcmntFxVS49Jt
      - key: DAILY_API_KEY
        value: d19964998b42867784f5ee7e9cf95ee4a05c044861b44aae14754eaa5fb47876
      - key: STREAM_API_KEY
        value: djqf3q9q4ygj
      - key: STREAM_SECRET_KEY
        value: rtv72856wrcq4946hv6srztkdgyqnh7xcrwnhse5r8f7aj7zhfp7ycnrkffmhfp5
        
  # API Gateway
  - type: web
    name: pronet-api-gateway
    runtime: node
    plan: free
    rootDir: services/api-gateway
    buildCommand: npm install --production=false --legacy-peer-deps && npm run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 3000
      - key: USER_SERVICE_URL
        fromService:
          type: web
          name: pronet-user-service
          property: hostport
      - key: JWT_SECRET
        value: "VY2Lf3iix4PILDFNK7HggRhhHIiyQY3qB381Cq0Yui0="


